@startuml

package "React Application" {
    component App {
        component Header {
            component NavBar {
                component "Logo" as Logo
                component "Link to About" as LAbout
                component "Link to Blog" as LBlog
                component "Link to Education" as LEducation
                component "Link to Project" as LProject
                component "Link to Gallery" as LGallery
                component "Link to VideoGallery" as LVideoGallery
                component "Link to Contact" as LContact
            }
        }
        component Main {
            component Routes {
                component "Route to About" as RAbout
                component "Route to Blog" as RBlog {
                    component "Blog" as Blog {
                        component "Photo Links" as PhotoLinks {
                            component "Link to Businessshot" as LBizShot
                            component "Link to Aestheticshot" as LAestheticShot
                            component "Link to Reflectsshot" as LReflectsShot
                        }
                    }
                    component "Route to Businessshot" as RBizShot
                    component "Route to Aestheticshot" as RAestheticShot
                    component "Route to Reflectsshot" as RReflectsShot
                }
                component "Route to Education" as REducation
                component "Route to Project" as RProject
                component "Route to Gallery" as RGallery
                component "Route to VideoGallery" as RVideoGallery
                component "Route to Contact" as RContact
            }
        }
        component Footer {
            component "Copyright 2024 Meiqi Cheng" as Copyright
        }
    }
}

' Connections from NavBar Links to Routes
LAbout ..> RAbout : navigates to
LBlog ..> RBlog : navigates to
LEducation ..> REducation : navigates to
LProject ..> RProject : navigates to
LGallery ..> RGallery : navigates to
LVideoGallery ..> RVideoGallery : navigates to
LContact ..> RContact : navigates to

' Connections from Blog to individual image detail pages
LBizShot ..> RBizShot : navigates to "Businessshot"
LAestheticShot ..> RAestheticShot : navigates to "Aestheticshot"
LReflectsShot ..> RReflectsShot : navigates to "Reflectsshot"

@enduml
